### ISSUE TITLE
xagent-ToolServerMonitor-1 fails to start - authentication error

### ISSUE THREAD

**Issue by mudislandkid** [OpenBMB/XAgent#129]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
After I've set my environment variables for API keys etc and built the containers, when I use docker-compose up the xagent-ToolServerMonitor-1 container fails immediately with the following error:

`pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}`

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

Follow the instructions as written to setup the docker environment and start the containers.

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

All containers should run without errors or exiting

## Environment / 环境信息
- Operating System / 操作系统：MacOSX
- Python Version / Python 版本：3.9.18
- Other Relevant Information / 其他相关信息：
- running in a conda venv

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

I've checked that the database credentials specified in the config file are being pulled correctly into the container by exec into the container and echo ing the variables.

Log Output:

`INFO:    Database connected
INFO:    Docker client connected
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    asyncio.run(check_nodes_status_loop())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 42, in check_nodes_status_loop
    await check_nodes_status()
  File "/app/main.py", line 12, in check_nodes_status
    async for node in nodes:
  File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 1390, in next
    if self.alive and (self._buffer_size() or await self._get_more()):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1179, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.10/site-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1388, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1526, in _retryable_read
    with self._conn_from_server(read_pref, server, session) as (
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1324, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1246, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1598, in checkout
    conn = self._get_conn(handler=handler)
  File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1714, in _get_conn
    conn = self.connect(handler=handler)
  File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1568, in connect
    conn.authenticate()
  File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1042, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 616, in authenticate
    auth_func(credentials, conn)
  File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 521, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
  File "/usr/local/lib/python3.10/site-packages/pymongo/auth.py", line 248, in _authenticate_scram
    res = conn.command(source, cmd)
  File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File "/usr/local/lib/python3.10/site-packages/pymongo/network.py", line 191, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 223, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}`

**Comment by luyaxi** [comment]
Please make sure your password for mongodb does not contain any special char
