### ISSUE TITLE
KeyError: 'Could not automatically map gpt-4 to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'

### ISSUE THREAD

**Issue by huxinggg** [OpenBMB/XAgent#132]
Traceback (most recent call last):
  File "/data/project/XAgent/run.py", line 52, in <module>
    cmd.start(
  File "/data/project/XAgent/command.py", line 163, in start
    self.run({
  File "/data/project/XAgent/command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/root/anaconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/project/XAgent/XAgentServer/server.py", line 23, in interact
    from XAgent.agent import (PlanGenerateAgent, PlanRefineAgent,
  File "/data/project/XAgent/XAgent/agent/__init__.py", line 1, in <module>
    from .plan_generate_agent import PlanGenerateAgent
  File "/data/project/XAgent/XAgent/agent/plan_generate_agent/__init__.py", line 1, in <module>
    from .agent import PlanGenerateAgent
  File "/data/project/XAgent/XAgent/agent/plan_generate_agent/agent.py", line 2, in <module>
    from XAgent.agent.base_agent import BaseAgent
  File "/data/project/XAgent/XAgent/agent/base_agent.py", line 8, in <module>
    from XAgent.utils import LLMStatusCode, RequiredAbilities
  File "/data/project/XAgent/XAgent/utils.py", line 13, in <module>
    encoding = tiktoken.encoding_for_model(CONFIG.default_completion_kwargs['model'])
  File "/root/anaconda3/lib/python3.10/site-packages/tiktoken/model.py", line 68, in encoding_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4 to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'

**Comment by Umpire2018** [comment]
Can you provide more specific description with your  your config file in a new issue? 
Please remove sensitive information before you submit the issue.

**Comment by huxinggg** [comment]
> Can you provide more specific description with your your config file in a new issue? Please remove sensitive information before you submit the issue.

<img width="742" alt="image" src="https://github.com/OpenBMB/XAgent/assets/120166830/63ac1596-bc8f-42b8-9293-fb2d61650b12">

**Comment by Umpire2018** [comment]
内容不要重复，仅保留一个
```yml 
 gpt-4-32k:
    - api_key: sk-xxxxx
      model: gpt-4-32k
```

**Comment by huxinggg** [comment]
<img width="1011" alt="image" src="https://github.com/OpenBMB/XAgent/assets/120166830/9bc3e875-1921-4eff-805c-fafaa5abedd4">

**Comment by Umpire2018** [comment]
That's strange. I cann't reproduce your error.
![image](https://github.com/OpenBMB/XAgent/assets/138990495/c898e194-8bf9-4186-ba50-f9556ecf1986)

I believe there's somewhere wrong in your `config.yml` 
Maybe modify mine and retry
```
api_keys:
  gpt-4-32k:
    - api_key: sk-xxxxx
      model: gpt-4-32k

default_request_type: openai # or xagent
default_completion_kwargs:
  model: gpt-4-32k
  temperature: 0.2
  request_timeout: 60
  ```
If you still have error, can you zip your `config.yml` with your username `huxinggg` as password then send it to <a href="mailto:Arno.Edwards@outlook.com">my address</a>?
Please send the modified file so that i can debug with.
