### ISSUE TITLE
请问代理应该设置在哪个容器，访问duckduckgo报错

### ISSUE THREAD

**Issue by isunfloweryg** [OpenBMB/XAgent#210]
我把代理环境变量设置在ToolServerNode容器里，在容器里是可以访问duckduckgo的，但是执行xagent的应用程序在访问duckduckgo时就报错

**Comment by isunfloweryg** [comment]
还有个问题，执行工具的日志打印在哪里？我用docker logs看也没有输出，貌似也没有看到重定向的地方，代码确定是已经执行到xagent/ToolServer/ToolServerNode/main.py的excute_tool请求里了

**Comment by luyaxi** [comment]
toolservernode容器是动态创建的，请为本机设置全局代理以使用duckduckgo，或申请azure bing api key来使用bing搜搜

**Comment by simplecellzg** [comment]
使用ubuntu22.04，添加了全局代理之后出现了502网关错误，如下，取消代理之后就能正常运行，就是也不能联网搜索。
ToolServer connected in  http://localhost:8080
Traceback (most recent call last):
  File "/home/ubuntu/autoagent/XAgent-main/XAgent/tool_call_handle.py", line 194, in get_available_tools
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://localhost:8080/get_available_tools

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/autoagent/XAgent-main/run.py", line 64, in <module>
    cmd.start(
  File "/home/ubuntu/autoagent/XAgent-main/command.py", line 195, in start
    self.run({
  File "/home/ubuntu/autoagent/XAgent-main/command.py", line 166, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/autoagent/XAgent-main/XAgentServer/server.py", line 97, in interact
    subtask_functions, tool_functions_description_list = function_handler.get_functions(
  File "/home/ubuntu/autoagent/XAgent-main/XAgent/tool_call_handle.py", line 463, in get_functions
    output = toolserver_interface.get_available_tools()
  File "/home/ubuntu/autoagent/XAgent-main/XAgent/tool_call_handle.py", line 205, in get_available_tools
    raise Exception(f"Error when fetching available tools: {e}")
Exception: Error when fetching available tools: 502 Server Error: Bad Gateway for url: http://localhost:8080/get_available_tools
