### ISSUE TITLE
运行 run.py 时出现 Connection refused

### ISSUE THREAD

**Issue by Peter-Hamster** [OpenBMB/XAgent#215]
在运行完 docker-compose up --build ；pip install -r requirements.txt 之后，运行 python run.py --task "put your task here" --model "gpt-4" --config_file "assets/config.yml" 出现了几个问题：

ConnectionRefusedError: [Errno 111] Connection refused

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

请问这个问题如何解决？

************************************************************************************************************************************************
完整问题报告：

Human-In-The-Loop  False
ToolServer connected in  http://localhost:8080/
Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/peter/xagent/XAgent/run.py", line 52, in <module>
    cmd.start(
  File "/data/peter/xagent/XAgent/command.py", line 163, in start
    self.run({
  File "/data/peter/xagent/XAgent/command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/peter/xagent/XAgent/XAgentServer/server.py", line 65, in interact
    toolserver_interface.lazy_init(config=config)
  File "/data/peter/xagent/XAgent/XAgent/tool_call_handle.py", line 63, in lazy_init
    response = requests.post(f'{self.url}/get_cookie',)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused'))Human-In-The-Loop  False
ToolServer connected in  http://localhost:8080/
Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/peter/xagent/XAgent/run.py", line 52, in <module>
    cmd.start(
  File "/data/peter/xagent/XAgent/command.py", line 163, in start
    self.run({
  File "/data/peter/xagent/XAgent/command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/peter/xagent/XAgent/XAgentServer/server.py", line 65, in interact
    toolserver_interface.lazy_init(config=config)
  File "/data/peter/xagent/XAgent/XAgent/tool_call_handle.py", line 63, in lazy_init
    response = requests.post(f'{self.url}/get_cookie',)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/anaconda3/envs/xxxxxxx/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7377b198a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by luyaxi** [comment]
请检查ToolServer运行状态
