### ISSUE TITLE
The model `GPT-35-Turbo-16k` does not exist

### ISSUE THREAD

**Issue by Shiyao-Huang** [OpenBMB/XAgent#223]
## Issue Description / 问题描述
运行时执行到某一步出现The model `GPT-35-Turbo-16k` does not exist错误
```
openai.error.InvalidRequestError: The model `GPT-35-Turbo-16k` does not exist
2023-11-21 10:44:31 chatcompletion error: The model `GPT-35-Turbo-16k` does not exist 
2023-11-21 10:44:31 chatcompletion error: The model `GPT-35-Turbo-16k` does not exist 
2023-11-21 10:44:32 ERROR:    Exception in ASGI application
2023-11-21 10:44:32 Traceback (most recent call last):
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
2023-11-21 10:44:32     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-21 10:44:32     return await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2023-11-21 10:44:32     await super().__call__(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-11-21 10:44:32     await self.middleware_stack(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
2023-11-21 10:44:32     await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
2023-11-21 10:44:32     await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 26, in __call__
2023-11-21 10:44:32     await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-21 10:44:32     raise exc
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-21 10:44:32     await self.app(scope, receive, sender)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-21 10:44:32     raise e
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-21 10:44:32     await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-11-21 10:44:32     await route.handle(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
2023-11-21 10:44:32     await self.app(scope, receive, send)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 88, in dispatch
2023-11-21 10:44:32     raise exc
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 80, in dispatch
2023-11-21 10:44:32     await self.on_receive(websocket, data)
2023-11-21 10:44:32   File "/app/app.py", line 668, in on_receive
2023-11-21 10:44:32     await asyncio.create_task(self.do_running_long_task(parameter))
2023-11-21 10:44:32   File "/app/app.py", line 738, in do_running_long_task
2023-11-21 10:44:32     await task
2023-11-21 10:44:32   File "/app/XAgentServer/server.py", line 138, in interact
2023-11-21 10:44:32     raise e
2023-11-21 10:44:32   File "/app/XAgentServer/server.py", line 135, in interact
2023-11-21 10:44:32     await task_handler.outer_loop_async()
2023-11-21 10:44:32   File "/app/XAgent/workflow/task_handler.py", line 133, in outer_loop_async
2023-11-21 10:44:32     search_method = await self.inner_loop_async(self.now_dealing_task)
2023-11-21 10:44:32   File "/app/XAgent/workflow/task_handler.py", line 231, in inner_loop_async
2023-11-21 10:44:32     await search_method.run_async(config=self.config,
2023-11-21 10:44:32   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 95, in run_async
2023-11-21 10:44:32     await self.generate_chain_async(config, agent, task_handler, arguments,functions, task_id)
2023-11-21 10:44:32   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 287, in generate_chain_async
2023-11-21 10:44:32     tool_output, tool_output_status_code, need_for_plan_refine, using_tools = function_handler.handle_tool_call(
2023-11-21 10:44:32   File "/app/XAgent/tool_call_handle.py", line 567, in handle_tool_call
2023-11-21 10:44:32     command_result = self.long_result_summary({'name': command_name, 'arguments': arguments}, command_result)
2023-11-21 10:44:32   File "/app/XAgent/tool_call_handle.py", line 505, in long_result_summary
2023-11-21 10:44:32     ret['page'] = thd.result()
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2023-11-21 10:44:32     return self.__get_result()
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-11-21 10:44:32     raise self._exception
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2023-11-21 10:44:32     result = self.fn(*self.args, **self.kwargs)
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/function_manager.py", line 151, in __call__
2023-11-21 10:44:32     return self.execute(function_name,return_generation_usage,**kwargs)
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/function_manager.py", line 105, in execute
2023-11-21 10:44:32     response = objgenerator.chatcompletion(
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
2023-11-21 10:44:32     return self(f, *args, **kw)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
2023-11-21 10:44:32     do = self.iter(retry_state=retry_state)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
2023-11-21 10:44:32     return fut.result()
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
2023-11-21 10:44:32     return self.__get_result()
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-11-21 10:44:32     raise self._exception
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
2023-11-21 10:44:32     result = fn(*args, **kwargs)
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/request/obj_generator.py", line 64, in chatcompletion
2023-11-21 10:44:32     raise e
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/request/obj_generator.py", line 58, in chatcompletion
2023-11-21 10:44:32     response = self._get_chatcompletion_request_func(request_type)(**kwargs)
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/request/openai.py", line 58, in chatcompletion_request
2023-11-21 10:44:32     raise e
2023-11-21 10:44:32   File "/app/XAgent/ai_functions/request/openai.py", line 35, in chatcompletion_request
2023-11-21 10:44:32     response = openai.ChatCompletion.create(**chatcompletion_kwargs)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
2023-11-21 10:44:32     return super().create(*args, **kwargs)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
2023-11-21 10:44:32     response, _, api_key = requestor.request(
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
2023-11-21 10:44:32     resp, got_stream = self._interpret_response(result, stream)
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
2023-11-21 10:44:32     self._interpret_response_line(
2023-11-21 10:44:32   File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
2023-11-21 10:44:32     raise self.handle_error_response(
2023-11-21 10:44:32 openai.error.InvalidRequestError: The model `GPT-35-Turbo-16k` does not exist
2023-11-21 10:44:32 INFO:     connection closed
```

## Environment / 环境信息
- MAC OS / 操作系统：
- 3.10 / Python 版本：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
配置文件：
![image](https://github.com/OpenBMB/XAgent/assets/102647710/4a17017d-cbff-4086-903b-9531202ad5e2)

**Comment by sailaoda** [comment]
Hello, please let the model be the same as the api_key`s name. Just like yours: gpt-3.5-turbo-16k

![image](https://github.com/OpenBMB/XAgent/assets/44259537/8cb600d8-5cdc-4341-89cd-d7721fde6eb1)

**Comment by Shiyao-Huang** [comment]
谢谢
