### ISSUE TITLE
Error: `Identifier 'userInfo' has already been declared. (28:12)` happend when using `/bin/sh -c npm run build`

### ISSUE THREAD

**Issue by Umpire2018** [OpenBMB/XAgent#246]
## Issue Description / 问题描述
When using `docker compose -f "docker-compose.yml" up -d --build` , this error happened.

## Steps to Reproduce / 复现步骤
Running command `docker compose -f "docker-compose.yml" up -d --build`

## Environment / 环境信息
- Operating System / 操作系统：WSL2 ubuntu on windows
- Other Relevant Information / 其他相关信息：Lastest code (Clone at 21:50 2023/11/23 CST) 

## Error Screenshots or Logs / 错误截图或日志

```
 => ERROR [XAgentServer xagentweb 6/6] RUN npm run build                                                                                                   3.8s
 => [ToolServerNode  5/12] RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple                                                    1.6s
 => CANCELED [ToolServerNode  6/12] RUN pip install playwright && playwright install chromium &&  playwright install-deps                                  1.0s
------
 > [XAgentServer xagentweb 6/6] RUN npm run build:
0.744 
0.744 > xagent@0.0.0 build
0.744 > vite build --mode production
0.744 
1.281 command build mode production
1.281 
1.316 vite v4.5.0 building for production...
1.420 transforming...
3.758 ✓ 279 modules transformed.
3.760 ✓ built in 2.44s
3.760 
3.760  ERROR  [vite:vue] [vue/compiler-sfc] Identifier 'userInfo' has already been declared. (28:12)
3.760 
3.760 /app/src/views/playground/components/HistorySidebar.vue
3.760 175|  
3.760 176|  const {
3.760 177|    userInfo: userInfo
3.760    |              ^
3.760 178|  } = storeToRefs(userStore)
3.760 179|  
3.760 file: /app/src/views/playground/components/HistorySidebar.vue:28:12
3.760 
3.761 
3.761  ERROR  error during build:
3.761 SyntaxError: [vue/compiler-sfc] Identifier 'userInfo' has already been declared. (28:12)
3.761 
3.761 /app/src/views/playground/components/HistorySidebar.vue
3.761 175|  
3.761 176|  const {
3.761 177|    userInfo: userInfo
3.761    |              ^
3.761 178|  } = storeToRefs(userStore)
3.761 179|  
3.761     at constructor (/app/node_modules/@babel/parser/lib/index.js:356:19)
3.761     at TypeScriptParserMixin.raise (/app/node_modules/@babel/parser/lib/index.js:3223:19)
3.761     at TypeScriptScopeHandler.checkRedeclarationInScope (/app/node_modules/@babel/parser/lib/index.js:1496:19)
3.761     at TypeScriptScopeHandler.declareName (/app/node_modules/@babel/parser/lib/index.js:1467:12)
3.761     at TypeScriptScopeHandler.declareName (/app/node_modules/@babel/parser/lib/index.js:7052:11)
3.761     at TypeScriptParserMixin.declareNameFromIdentifier (/app/node_modules/@babel/parser/lib/index.js:7484:16)
3.761     at TypeScriptParserMixin.checkIdentifier (/app/node_modules/@babel/parser/lib/index.js:7480:12)
3.761     at TypeScriptParserMixin.checkLVal (/app/node_modules/@babel/parser/lib/index.js:7419:12)
3.761     at TypeScriptParserMixin.checkLVal (/app/node_modules/@babel/parser/lib/index.js:7450:14)
3.761     at TypeScriptParserMixin.checkLVal (/app/node_modules/@babel/parser/lib/index.js:7450:14)
3.761 
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
 ```

**Comment by shanmu-raoyunfei** [comment]
same here

**Comment by CCMKCCMK** [comment]
same here

**Comment by zhaotaotao3276** [comment]
delete these
_const {
  userInfo: userInfo
} = storeToRefs(userStore)

// const isBetaUser = computed(() => userInfo.value?.is_beta === true ? true : false)
const isBetaUser = computed(() => true)



const {
  userInfo: userInfo
} = storeToRefs(userStore)

167行_

**Comment by ChengFai** [comment]
OK谢谢，这个是因为合并代码冲突的时候没有解决这一块导致的，已解决，请拉最新代码
