### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './assets/config/manager.yml'

### ISSUE THREAD

**Issue by jfo888** [OpenBMB/XAgent#280]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [1] [INFO] Starting gunicorn 21.2.0
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [7] [INFO] Booting worker with pid: 7
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [8] [INFO] Booting worker with pid: 8
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [9] [INFO] Booting worker with pid: 9
2023-11-30 12:48:31 [2023-11-30 04:48:31 +0000] [10] [INFO] Booting worker with pid: 10
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [10] [ERROR] Exception in worker process
2023-11-30 12:48:35 Traceback (most recent call last):
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-11-30 12:48:35     worker.init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-11-30 12:48:35     super(UvicornWorker, self).init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-11-30 12:48:35     self.load_wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-11-30 12:48:35     self.wsgi = self.app.wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-11-30 12:48:35     self.callable = self.load()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-11-30 12:48:35     return self.load_wsgiapp()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-11-30 12:48:35     return util.import_app(self.app_uri)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-11-30 12:48:35     mod = importlib.import_module(module)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-11-30 12:48:35     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-11-30 12:48:35   File "/app/main.py", line 12, in <module>
2023-11-30 12:48:35     from config import CONFIG,logger,MANAGER_ID
2023-11-30 12:48:35   File "/app/config.py", line 65, in <module>
2023-11-30 12:48:35     CONFIG = ManagerConfig()
2023-11-30 12:48:35   File "/app/config.py", line 27, in __init__
2023-11-30 12:48:35     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-11-30 12:48:35 FileNotFoundError: [Errno 2] No such file or directory: './assets/config/manager.yml'
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [7] [ERROR] Exception in worker process
2023-11-30 12:48:35 Traceback (most recent call last):
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-11-30 12:48:35     worker.init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-11-30 12:48:35     super(UvicornWorker, self).init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-11-30 12:48:35     self.load_wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-11-30 12:48:35     self.wsgi = self.app.wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-11-30 12:48:35     self.callable = self.load()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-11-30 12:48:35     return self.load_wsgiapp()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-11-30 12:48:35     return util.import_app(self.app_uri)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-11-30 12:48:35     mod = importlib.import_module(module)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-11-30 12:48:35     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-11-30 12:48:35   File "/app/main.py", line 12, in <module>
2023-11-30 12:48:35     from config import CONFIG,logger,MANAGER_ID
2023-11-30 12:48:35   File "/app/config.py", line 65, in <module>
2023-11-30 12:48:35     CONFIG = ManagerConfig()
2023-11-30 12:48:35   File "/app/config.py", line 27, in __init__
2023-11-30 12:48:35     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-11-30 12:48:35 FileNotFoundError: [Errno 2] No such file or directory: './assets/config/manager.yml'
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [9] [ERROR] Exception in worker process
2023-11-30 12:48:35 Traceback (most recent call last):
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-11-30 12:48:35     worker.init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-11-30 12:48:35     super(UvicornWorker, self).init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-11-30 12:48:35     self.load_wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-11-30 12:48:35     self.wsgi = self.app.wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-11-30 12:48:35     self.callable = self.load()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-11-30 12:48:35     return self.load_wsgiapp()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-11-30 12:48:35     return util.import_app(self.app_uri)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-11-30 12:48:35     mod = importlib.import_module(module)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-11-30 12:48:35     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-11-30 12:48:35   File "/app/main.py", line 12, in <module>
2023-11-30 12:48:35     from config import CONFIG,logger,MANAGER_ID
2023-11-30 12:48:35   File "/app/config.py", line 65, in <module>
2023-11-30 12:48:35     CONFIG = ManagerConfig()
2023-11-30 12:48:35   File "/app/config.py", line 27, in __init__
2023-11-30 12:48:35     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-11-30 12:48:35 FileNotFoundError: [Errno 2] No such file or directory: './assets/config/manager.yml'
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [8] [ERROR] Exception in worker process
2023-11-30 12:48:35 Traceback (most recent call last):
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-11-30 12:48:35     worker.init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-11-30 12:48:35     super(UvicornWorker, self).init_process()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-11-30 12:48:35     self.load_wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-11-30 12:48:35     self.wsgi = self.app.wsgi()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-11-30 12:48:35     self.callable = self.load()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-11-30 12:48:35     return self.load_wsgiapp()
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-11-30 12:48:35     return util.import_app(self.app_uri)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-11-30 12:48:35     mod = importlib.import_module(module)
2023-11-30 12:48:35   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-11-30 12:48:35     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-11-30 12:48:35   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-11-30 12:48:35   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-11-30 12:48:35   File "/app/main.py", line 12, in <module>
2023-11-30 12:48:35     from config import CONFIG,logger,MANAGER_ID
2023-11-30 12:48:35   File "/app/config.py", line 65, in <module>
2023-11-30 12:48:35     CONFIG = ManagerConfig()
2023-11-30 12:48:35   File "/app/config.py", line 27, in __init__
2023-11-30 12:48:35     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-11-30 12:48:35 FileNotFoundError: [Errno 2] No such file or directory: './assets/config/manager.yml'
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [7] [INFO] Worker exiting (pid: 7)
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [10] [INFO] Worker exiting (pid: 10)
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [9] [INFO] Worker exiting (pid: 9)
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Worker (pid:9) was sent SIGTERM!
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Worker (pid:10) was sent SIGTERM!
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Worker (pid:8) was sent SIGTERM!
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Shutting down: Master
2023-11-30 12:48:35 [2023-11-30 04:48:35 +0000] [1] [ERROR] Reason: Worker failed to boot.
## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。
在toolserver目录下运行docker-compose up，会显示找不到manager.yml，导致无法启动，请问是什么原因
然后XAgent的主页面总是登录失败，不管输入的什么账号密码都提示失败

**Comment by Umpire2018** [comment]
请在根目录下而不是 toolserver目录下运行 `docker-compose up`

**Comment by Umpire2018** [comment]
我们无法复现这个问题，请保证本地与远程保持一致，同时可以删除原有的 docker image，container 进行重试。
