### ISSUE TITLE
运行报错AttributeError: 'ToolServerInterface' object has no attribute 'cookies

### ISSUE THREAD

**Issue by iDonal** [OpenBMB/XAgent#284]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
在web页面提问后页面卡主，后台显示报错。  

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
通过docker拉取远程镜像部署， 服务启动正常

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
web页面有 信息返回

## Environment / 环境信息
- Operating System / 操作系统： MacOs
- Python Version / Python 版本： python 3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

```
XAgent-Server               | INFO:     Will watch for changes in these directories: ['/app']
XAgent-Server               | INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
XAgent-Server               | INFO:     Started reloader process [1] using StatReload
XAgent-Server               | INFO:     Started server process [17]
XAgent-Server               | INFO:     Waiting for application startup.
XAgent-Server               | INFO:     Application startup complete.
XAgent-Server               |   XAgent Service Startup Param:
XAgent-Server               |             app: app:app
XAgent-Server               |             prod: False
XAgent-Server               |             base_dir: XAgentServer
XAgent-Server               |             use_redis: False
XAgent-Server               |             recorder_root_dir: running_records
XAgent-Server               |             default_login: True
XAgent-Server               |             check_running: False
XAgent-Server               |             host: 0.0.0.0
XAgent-Server               |             port: 8090
XAgent-Server               |             debug: True
XAgent-Server               |             reload: True
XAgent-Server               |             workers: 1
XAgent-Server               |             share_url: https://x-agent.net/api/conv/community
XAgent-Server               |             DB: <class 'XAgentServer.application.core.envs.XAgentServerEnv.DB'>
XAgent-Server               |             Redis: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Redis'>
XAgent-Server               |             Email: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Email'>
XAgent-Server               |             Upload: <class 'XAgentServer.application.core.envs.XAgentServerEnv.Upload'>
XAgent-Server               | XAgent Service Init Dependence.
XAgent-Server               | init a thread pool executor, max_workers: 1
XAgent-Server               | XAgent Service Init Dependence: Complete!
XAgent-Server               | Default user: Guest, token: xagent, you can use it to login
XAgent-Server               | XAgent Server Dependences:
XAgent-Server               |         Python: 3.10+
XAgent-Server               |         FastAPI: Http server
XAgent-Server               |         Websocket: long connect with client
XAgent-Server               |         MySQL: save xagent data
XAgent-Server               |         SqlAlchemy: ORM with MySQL
XAgent-Server               |         Redis: save status of interaction
XAgent-Server               |         Threading: run interaction
XAgent-Server               |         APScheduler: send data to client and keep alive
XAgent-Server               |         FastAPI APIRouter: manage websocket route
XAgent-Server               |         XAgentError: XAgentServer.exts.exception_ext
XAgent-Server               | XAgent Server Version:
XAgent-Server               |         V 1.1.0
XAgent-Server               | Notes:
XAgent-Server               |         Since V 1.1.0,
XAgent-Server               |         Local storage will no longer be supported, replaced by Mysql.
XAgent-Server               |         The service depends on Redis and Mysql,
XAgent-Server               |         so you need to install Redis and Mysql before using it.
XAgent-Server               |         Before you use this service, please ensure that the following services are available:
XAgent-Server               |             1. Redis on docker, port: 6379, you can start it by docker, default password: xagent
XAgent-Server               |             2. Mysql on docker, port: 3306, you can start it by docker
XAgent-Server               |             3. XAgent Tool Server is runnning on port 8080
XAgent-Server               |             4. Port 8090 is not occupied
XAgent-Server               |
XAgent-Server               | INFO:     127.0.0.1:52552 - "POST /conv/getUserInteractions HTTP/1.0" 200 OK
XAgent-Server               | INFO:     127.0.0.1:52550 - "POST /conv/init_conv_env HTTP/1.0" 200 OK
XAgent-Server               | INFO:     ('172.20.0.1', 49130) - "WebSocket /ws/base/d8561716baea4077ab76f500ef3d321e?user_id=guest&token=xagent&description=Create%20a%20program%20that%20gene" [accepted]
XAgent-Server               | INFO:     connection open
XAgent-Server               | Receive connection from d8561716baea4077ab76f500ef3d321e:   user_id: guest, token: xagent, description: Create a program that gene
XAgent-Server               | Receive data from d8561716baea4077ab76f500ef3d321e:   {
XAgent-Server               |     "type": "data",
XAgent-Server               |     "args": {
XAgent-Server               |         "goal": "Create a program that generates personalized reading recommendations based on a user's favorite authors and genres. Test the program with various user profiles and provide a report on the accuracy and diversity of the recommendations."
XAgent-Server               |     },
XAgent-Server               |     "agent": "agent",
XAgent-Server               |     "mode": "auto",
XAgent-Server               |     "file_list": []
XAgent-Server               | }
XAgent-Server               | Receive data from d8561716baea4077ab76f500ef3d321e:   {
XAgent-Server               |     "type": "connect"
XAgent-Server               | }
XAgent-Server               |   init interaction: d8561716baea4077ab76f500ef3d321e
XAgent-Server               |   Register logger into interaction of d8561716baea4077ab76f500ef3d321e, done!
XAgent-Server               |   Register db into interaction of d8561716baea4077ab76f500ef3d321e, done!
XAgent-Server               |   Register logger into XAgentServer of d8561716baea4077ab76f500ef3d321e, done!
XAgent-Server               |   Start a new thread to run interaction of d8561716baea4077ab76f500ef3d321e, done!
XAgent-Server               | ---config file---
XAgent-Server               | assets/config.yml
XAgent-Server               | ---args---
XAgent-Server               | {}
XAgent-Server               |   server is running, the start query is Create a program that generates personalized reading recommendations based on a user's favorite authors and genres. Test the program with various user profiles and provide a report on the accuracy and diversity of the recommendations.
XAgent-Server               |   register tool server interface
XAgent-Server               |   lazy init tool server interface
XAgent-Server               | Trying
XAgent-Server               | to
XAgent-Server               | connect
XAgent-Server               | to
XAgent-Server               | ToolServer
XAgent-Server               | at
XAgent-Server               |
XAgent-Server               | http://ToolServerManager:8080
xagent-ToolServerManager-1  | [2023-11-30 11:41:25 +0000] [7] [INFO] Node created: 93710ac9809c70f0e636802d340bc632c56b06b8a60353af7ff41127dd8035ce
xagent-ToolServerManager-1  | [2023-11-30 11:41:55 +0000] [7] [WARNING] Node status detection timeout: 93710ac9809c70f0e636802d340bc632c56b06b8a60353af7ff41127dd8035ce
XAgent-Server               | Exception in thread Thread-1 (task_handler):
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 52, in interact
XAgent-Server               |     xagent_core.build(xagent_param, interaction=interaction)
XAgent-Server               |   File "/app/XAgent/core.py", line 198, in build
XAgent-Server               |     self.register_all(param, interaction)
XAgent-Server               |   File "/app/XAgent/core.py", line 188, in register_all
XAgent-Server               |     self.register_toolserver_interface(param)
XAgent-Server               |   File "/app/XAgent/core.py", line 141, in register_toolserver_interface
XAgent-Server               |     self.toolserver_interface.lazy_init(config=param.config)
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 94, in lazy_init
XAgent-Server               |     response.raise_for_status()
XAgent-Server               |   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
XAgent-Server               |     raise HTTPError(http_error_msg, response=self)
XAgent-Server               | requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://toolservermanager:8080/get_cookie
XAgent-Server               |
XAgent-Server               | The above exception was the direct cause of the following exception:
XAgent-Server               |
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 93, in interact
XAgent-Server               |     raise XAgentRunningError(str(e)) from e
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentRunningError: 503 Server Error: Service Unavailable for url: http://toolservermanager:8080/get_cookie
XAgent-Server               |
XAgent-Server               | During handling of the above exception, another exception occurred:
XAgent-Server               |
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
XAgent-Server               |
XAgent-Server               |     self.run()
XAgent-Server               |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
XAgent-Server               |     self._target(*self._args, **self._kwargs)
XAgent-Server               |   File "/app/XAgentServer/application/websockets/base.py", line 324, in task_handler
XAgent-Server               |     server.interact(interaction=interaction)
XAgent-Server               |   File "/app/XAgentServer/server.py", line 96, in interact
XAgent-Server               |     xagent_core.close()
XAgent-Server               |   File "/app/XAgent/core.py", line 216, in close
XAgent-Server               |     self.toolserver_interface.download_all_files()
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 166, in download_all_files
XAgent-Server               |     response = requests.post(url, cookies=self.cookies,)
XAgent-Server               | AttributeError: 'ToolServerInterface' object has no attribute 'cookies'```

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by glayyiyi** [comment]
看起来XAgent初始化与ToolServerManager服务的通信时失败。可以试试以下几件事:

1. 检查ToolServerManager服务是否在运行:

```
docker-compose ps
```

应该可以看到ToolServerManager服务被列为Up状态。


2. 如果未在运行,重新启动它:

```  
docker-compose restart ToolServerManager
```

3. 检查ToolServerManager服务的日志:

```
docker-compose logs ToolServerManager
```

查看是否有任何错误或服务失败启动的迹象。


4. 试着重建容器:

```
docker-compose down  
docker-compose build
docker-compose up
```

5. 确保docker-compose.yml中ToolServerManager服务暴露了8080端口,以便XAgent可以访问。


6. 验证XAgent容器内是否可以解析主机名`toolservermanager`。


7. 最后手段,清理所有容器和镜像,然后从头开始重建。


主要检查的要点:
- ToolServerManager正在运行
- 8080端口暴露正确  
- 网络允许XAgent访问它

如果需要任何步骤的更多详细信息或有其他问题,请告知我。

**Comment by Umpire2018** [comment]
@glayyiyi 需要排查根本原因，在 [此处](https://github.com/OpenBMB/XAgent/issues?q=is%3Aissue+cookies) 可以看到，不同用户报告了类似问题，所有我重新打开了此issue，希望给其他人作为参考。

**Comment by glayyiyi** [comment]
@iDonal ,请问你按上述方式尝试后，还会有该问题出现么？ 另外可以参考下已关闭的issue下面的回复作为参考：https://github.com/OpenBMB/XAgent/issues/262
如还有其他问题，可再联系我们。
