### ISSUE TITLE
'DotDict' object has no attribute 'default_completion_kwargs'

### ISSUE THREAD

**Issue by jfo888** [OpenBMB/XAgent#296]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
2023-12-03 22:35:44 INFO:     Will watch for changes in these directories: ['/app']
2023-12-03 22:35:44 INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
2023-12-03 22:35:44 INFO:     Started reloader process [1] using StatReload
2023-12-03 22:35:50 Process SpawnProcess-1:
2023-12-03 22:35:50 Traceback (most recent call last):
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-12-03 22:35:50     self.run()
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-12-03 22:35:50     self._target(*self._args, **self._kwargs)
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
2023-12-03 22:35:50     target(sockets=sockets)
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
2023-12-03 22:35:50     return asyncio.run(self.serve(sockets=sockets))
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-12-03 22:35:50     return loop.run_until_complete(main)
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2023-12-03 22:35:50     return future.result()
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
2023-12-03 22:35:50     config.load()
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
2023-12-03 22:35:50     self.loaded_app = import_from_string(self.app)
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
2023-12-03 22:35:50     module = importlib.import_module(module_str)
2023-12-03 22:35:50   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-12-03 22:35:50     return _bootstrap._gcd_import(name[level:], package, level)
2023-12-03 22:35:50   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-12-03 22:35:50   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-12-03 22:35:50   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-12-03 22:35:50   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-12-03 22:35:50   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-12-03 22:35:50   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-12-03 22:35:50   File "/app/XAgentServer/application/main.py", line 159, in <module>
2023-12-03 22:35:50     from XAgentServer.application.websockets import base, recorder, replayer, share
2023-12-03 22:35:50   File "/app/XAgentServer/application/websockets/base.py", line 40, in <module>
2023-12-03 22:35:50     from XAgentServer.interaction import XAgentInteraction
2023-12-03 22:35:50   File "/app/XAgentServer/interaction.py", line 12, in <module>
2023-12-03 22:35:50     from XAgent.toolserver_interface import ToolServerInterface
2023-12-03 22:35:50   File "/app/XAgent/toolserver_interface.py", line 9, in <module>
2023-12-03 22:35:50     from XAgent.logs import logger
2023-12-03 22:35:50   File "/app/XAgent/logs.py", line 15, in <module>
2023-12-03 22:35:50     from XAgent.utils import Singleton, TaskSaveItem
2023-12-03 22:35:50   File "/app/XAgent/utils.py", line 11, in <module>
2023-12-03 22:35:50     if CONFIG.default_completion_kwargs['model'] == "xagentllm":
2023-12-03 22:35:50   File "/app/XAgent/config.py", line 40, in __getattr__
2023-12-03 22:35:50     raise AttributeError(f"'DotDict' object has no attribute '{key}'")
2023-12-03 22:35:50 AttributeError: 'DotDict' object has no attribute 'default_completion_kwargs'
## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。
网页界面outer loop无反应

**Comment by Umpire2018** [comment]
目前我尝试了 XAgentGen 镜像，但未复现出这个错误，请您先尝试以上评论方法，若依旧遇到问题，请继续附上详细日志到文件中。

**Comment by linghanwu-code** [comment]
INFO:     Will watch for changes in these directories: ['/app']
XAgent-Server        | INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
XAgent-Server        | INFO:     Started reloader process [1] using WatchFiles
XAgent-Server        | Process SpawnProcess-1:
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
XAgent-Server        |     self.run()
XAgent-Server        |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
XAgent-Server        |     self._target(*self._args, **self._kwargs)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
XAgent-Server        |     target(sockets=sockets)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
XAgent-Server        |     return asyncio.run(self.serve(sockets=sockets))
XAgent-Server        |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
XAgent-Server        |     return loop.run_until_complete(main)
XAgent-Server        |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
XAgent-Server        |     await self._serve(sockets)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
XAgent-Server        |     config.load()
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
XAgent-Server        |     self.loaded_app = import_from_string(self.app)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
XAgent-Server        |     module = importlib.import_module(module_str)
XAgent-Server        |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
XAgent-Server        |     return _bootstrap._gcd_import(name[level:], package, level)
XAgent-Server        |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
XAgent-Server        |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
XAgent-Server        |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
XAgent-Server        |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
XAgent-Server        |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
XAgent-Server        |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
XAgent-Server        |   File "/app/XAgentServer/application/main.py", line 159, in <module>
XAgent-Server        |     from XAgentServer.application.websockets import base, recorder, replayer, share
XAgent-Server        |   File "/app/XAgentServer/application/websockets/base.py", line 40, in <module>
XAgent-Server        |     from XAgentServer.interaction import XAgentInteraction
XAgent-Server        |   File "/app/XAgentServer/interaction.py", line 12, in <module>
XAgent-Server        |     from XAgent.toolserver_interface import ToolServerInterface
XAgent-Server        |   File "/app/XAgent/toolserver_interface.py", line 9, in <module>
XAgent-Server        |     from XAgent.utils import ToolCallStatusCode
XAgent-Server        |   File "/app/XAgent/utils.py", line 11, in <module>
XAgent-Server        |     if CONFIG.default_completion_kwargs['model'] == "xagentllm":
XAgent-Server        |   File "/app/XAgent/config.py", line 40, in __getattr__
XAgent-Server        |     raise AttributeError(f"'DotDict' object has no attribute '{key}'")
