### ISSUE TITLE
run.py --task does't work as expected

### ISSUE THREAD

**Issue by Jeffwan** [OpenBMB/XAgent#30]
```
[ec2-user@ip-172-31-28-146 XAgent]$ python3 run.py --task "Help me find some japanese resturants in seattle area which price/person lower than $50" --model "gpt-4"
Traceback (most recent call last):
  File "/home/ec2-user/XAgent/run.py", line 5, in <module>
    from XAgent.config import CONFIG
  File "/home/ec2-user/XAgent/XAgent/config.py", line 39
    match model_name.lower():
          ^
SyntaxError: invalid syntax
```

**Comment by Jeffwan** [comment]
Sorry I notice I used Python 3.9. actually to support match syntax, Python 3.10 is required. This should be updated in the documentation
