### ISSUE TITLE
XAgentRunningError: Missing required arguments; Expected either ('messages' and 'model')

### ISSUE THREAD

**Issue by Lings01** [OpenBMB/XAgent#303]
Constructing an Agent:  PlanGenerateAgent
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
  chatcompletion: using gpt-4-32k
Traceback (most recent call last):
  File "/data/lrs_fgn/XAgent/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
    response = self._get_chatcompletion_request_func(request_type)(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/lrs_fgn/XAgent/XAgent/ai_functions/request/openai.py", line 161, in chatcompletion_request
    completions = client.chat.completions.create(**chatcompletion_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/openai/_utils/_utils.py", line 300, in wrapper
    raise TypeError(msg)
TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given
chatcompletion error: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given 
Traceback (most recent call last):
  File "/data/lrs_fgn/XAgent/XAgentServer/server.py", line 99, in interact
    task_handler.outer_loop()
  File "/data/lrs_fgn/XAgent/XAgent/workflow/task_handler.py", line 82, in outer_loop
    self.plan_agent.initial_plan_generation(
  File "/data/lrs_fgn/XAgent/XAgent/workflow/plan_exec.py", line 164, in initial_plan_generation
    new_message , _ = agent.parse(
                      ^^^^^^^^^^^^
  File "/data/lrs_fgn/XAgent/XAgent/agent/plan_generate_agent/agent.py", line 49, in parse
    return self.generate(
           ^^^^^^^^^^^^^^
  File "/data/lrs_fgn/XAgent/XAgent/agent/base_agent.py", line 121, in generate
    response = objgenerator.chatcompletion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/lrs_fgn/XAgent/XAgent/ai_functions/request/obj_generator.py", line 66, in chatcompletion
    raise e
  File "/data/lrs_fgn/XAgent/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
    response = self._get_chatcompletion_request_func(request_type)(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/data/lrs_fgn/XAgent/XAgent/ai_functions/request/openai.py", line 161, in chatcompletion_request
    completions = client.chat.completions.create(**chatcompletion_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data/lrs_fgn/.conda/envs/xagent/lib/python3.11/site-packages/openai/_utils/_utils.py", line 300, in wrapper
    raise TypeError(msg)
TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/lrs_fgn/XAgent/command.py", line 273, in task_handler
    server.interact(interaction=interaction)
  File "/data/lrs_fgn/XAgent/XAgentServer/server.py", line 101, in interact
    raise XAgentRunningError(str(e)) from e
XAgentServer.exts.exception_ext.XAgentRunningError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given
Error in task_handler of 24debbd70713488f84efc9423efddcc9: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given  
这个错误是什么意思呢，我config内容是这个：
<img width="700" alt="image" src="https://github.com/OpenBMB/XAgent/assets/41919779/20d96f61-a85a-4398-95dc-e7f61421d869">

**Comment by sailaoda** [comment]
您好，您可以将 config 内容中的 engine 改成 model 再次尝试

**Comment by sailaoda** [comment]
您好，已最新进行适配，您可以拉取最新代码采用您的原config进行使用

**Comment by Lings01** [comment]
我测试了一下，还是不行；需要对config作以下修改：
注释掉api_type；
将api_base改为azure_endpoint
才能正常运行

**Comment by sailaoda** [comment]
您好， 我这边按照您的config是可以的，请问您方便提供您的 openai python 包的版本以及您的操作系统版本等信息吗？ 在此之前您可以尝试 docker compose up --build 进行最新代码的本地构建使用，可能docker hub 镜像还未更新，期待您的回复。

**Comment by Lings01** [comment]
> 您好， 我这边按照您的config是可以的，请问您方便提供您的 openai python 包的版本以及您的操作系统版本等信息吗？ 在此之前您可以尝试 docker compose up --build 进行最新代码的本地构建使用，可能docker hub 镜像还未更新，期待您的回复。

我的openai版本是1.3.7,操作系统是ubuntu20.0.4

**Comment by sailaoda** [comment]
您好，已对 python 1.x 同时进行适配，您可以拉取最新代码采用您的原config进行使用
