### ISSUE TITLE
文件夹不存在，tool写入图片失败

### ISSUE THREAD

**Issue by fengyun99** [OpenBMB/XAgent#313]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
执行到中途产生文件不存在错误

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
上传iris.txt文件后，在前端执行“使用python分析iris.txt中数据，并生成汇报。”有概率触发错误，错误原因在于源码中文件夹不存在导致写入失败。

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
agent执行过程中能够正确的写入文件

## Environment / 环境信息
- Operating System / 操作系统：windows11，docker
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 102, in interact
XAgent-Server               |     task_handler.outer_loop()
relaxed_elgamal exited with code 0
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 138, in outer_loop
XAgent-Server               |     search_method = self.inner_loop(self.now_dealing_task)
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 241, in inner_loop
XAgent-Server               |     search_method.run(config=self.config,
XAgent-Server               |   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 104, in run
XAgent-Server               |     self.generate_chain(config, agent, arguments,
XAgent-Server               |   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 298, in generate_chain
XAgent-Server               |     tool_output, tool_output_status_code, need_for_plan_refine, using_tools = self.xagent_core_components.function_handler.handle_tool_call(
XAgent-Server               |   File "/app/XAgent/function_handler.py", line 214, in handle_tool_call
XAgent-Server               |     command_result, tool_output_status_code, = self.toolserver_interface.execute_command_client(
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 334, in execute_command_client
XAgent-Server               |     command_result = unwrap_tool_response(command_result, self.logger)
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in unwrap_tool_response
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in <listcomp>
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in unwrap_tool_response
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in <listcomp>
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 49, in unwrap_tool_response
XAgent-Server               |     with open(os.path.join('local_workspace', name), 'wb') as f:
XAgent-Server               | FileNotFoundError: [Errno 2] No such file or directory: 'local_workspace/db7bd16ba264466eb619dc996f2c679b.png'
XAgent-Server               |
XAgent-Server               | The above exception was the direct cause of the following exception:
XAgent-Server               |
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/application/websockets/base.py", line 324, in task_handler
XAgent-Server               |     server.interact(interaction=interaction)
XAgent-Server               |   File "/app/XAgentServer/server.py", line 104, in interact
XAgent-Server               |     raise XAgentRunningError(str(e)) from e
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentRunningError: [Errno 2] No such file or directory: 'local_workspace/db7bd16ba264466eb619dc996f2c679b.png'

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by dlmty** [comment]
我遇到了同样的问题。并且我全局查找不到local_workspace这个文件夹

**Comment by CaptainDP** [comment]
遇到了同样的问题：
描述：上传了execl，进行数据分析，中途出现了这个情况；
XAgent-Server               | Traceback (most recent call last):
XAgent-Server               |   File "/app/XAgentServer/server.py", line 105, in interact
XAgent-Server               |     task_handler.outer_loop()
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 138, in outer_loop
XAgent-Server               |     search_method = self.inner_loop(self.now_dealing_task)
XAgent-Server               |   File "/app/XAgent/workflow/task_handler.py", line 241, in inner_loop
XAgent-Server               |     search_method.run(config=self.config,
XAgent-Server               |   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 104, in run
XAgent-Server               |     self.generate_chain(config, agent, arguments,
XAgent-Server               |   File "/app/XAgent/inner_loop_search_algorithms/ReACT.py", line 298, in generate_chain
XAgent-Server               |     tool_output, tool_output_status_code, need_for_plan_refine, using_tools = self.xagent_core_components.function_handler.handle_tool_call(
XAgent-Server               |   File "/app/XAgent/function_handler.py", line 214, in handle_tool_call
XAgent-Server               |     command_result, tool_output_status_code, = self.toolserver_interface.execute_command_client(
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 334, in execute_command_client
XAgent-Server               |     command_result = unwrap_tool_response(command_result, self.logger)
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in unwrap_tool_response
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in <listcomp>
XAgent-Server               |     return [unwrap_tool_response(o, logger) for o in obj['data']]
XAgent-Server               |   File "/app/XAgent/toolserver_interface.py", line 56, in unwrap_tool_response
XAgent-Server               |   File "/app/XAgentServer/server.py", line 108, in interact
XAgent-Server               |     raise XAgentRunningError(str(e)) from e
XAgent-Server               | XAgentServer.exts.exception_ext.XAgentRunningError: [Errno 2] No such file or directory: 'local_workspace/02f95bfff6c441db91bdcd40da73e598.png'
musing_bassi exited with code 0
musing_bassi exited with code 0
xagent-ToolServerManager-1  | [2023-12-26 12:31:39 +0000] [9] [INFO] Node c3e6da187ab4 status updated: running -> exited
xagent-ToolServerManager-1  | [2023-12-26 12:31:39 +0000] [9] [INFO] Node c3e6da187ab4 health updated: healthy -> unhealthy

**Comment by eluyutao** [comment]
> 我遇到了同样的问题。并且我全局查找不到local_workspace这个文件夹

我也有这个No such file的问题，但是local_workspace这个文件夹不是在repo的根目录下吗
