### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jfo888** [OpenBMB/XAgent#330]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。

我将manager.yml放在E:\中，将E:\rengongzhineng\XAgent-main\ToolServer\ToolServerManager中的config.py的路径修改为def __init__(self, config_file_path=r"E:\manager.yml"):,然后在Cd E:\rengongzhineng\XAgent-main\Xagent文件夹下使用docker-compose build和docker-compose up，提示FileNotFoundError: [Errno 2] No such file or directory: 'E:\\manager.yml'，无论yml文件放在哪里，怎样修改路径都提示找不到文件

## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。

## Environment / 环境信息
- Operating System / 操作系统：
- Python Version / Python 版本：
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
```python
2023-12-11 13:13:02 [2023-12-11 05:13:02 +0000] [1] [INFO] Starting gunicorn 21.2.0
2023-12-11 13:13:02 [2023-12-11 05:13:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
2023-12-11 13:13:02 [2023-12-11 05:13:02 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
2023-12-11 13:13:03 [2023-12-11 05:13:03 +0000] [7] [INFO] Booting worker with pid: 7
2023-12-11 13:13:03 [2023-12-11 05:13:03 +0000] [8] [INFO] Booting worker with pid: 8
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [8] [ERROR] Exception in worker process
2023-12-11 13:13:31 Traceback (most recent call last):
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-12-11 13:13:31     worker.init_process()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-12-11 13:13:31     super(UvicornWorker, self).init_process()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-12-11 13:13:31     self.load_wsgi()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-12-11 13:13:31     self.wsgi = self.app.wsgi()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-12-11 13:13:31     self.callable = self.load()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-12-11 13:13:31     return self.load_wsgiapp()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-12-11 13:13:31     return util.import_app(self.app_uri)
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-12-11 13:13:31     mod = importlib.import_module(module)
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-12-11 13:13:31     return _bootstrap._gcd_import(name[level:], package, level)
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-12-11 13:13:31   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-12-11 13:13:31   File "/app/main.py", line 12, in <module>
2023-12-11 13:13:31     from config import CONFIG,logger,MANAGER_ID
2023-12-11 13:13:31   File "/app/config.py", line 65, in <module>
2023-12-11 13:13:31     CONFIG = ManagerConfig()
2023-12-11 13:13:31   File "/app/config.py", line 27, in __init__
2023-12-11 13:13:31     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-12-11 13:13:31 FileNotFoundError: [Errno 2] No such file or directory: 'E:\\manager.yml'
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [7] [ERROR] Exception in worker process
2023-12-11 13:13:31 Traceback (most recent call last):
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2023-12-11 13:13:31     worker.init_process()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/uvicorn/workers.py", line 66, in init_process
2023-12-11 13:13:31     super(UvicornWorker, self).init_process()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
2023-12-11 13:13:31     self.load_wsgi()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2023-12-11 13:13:31     self.wsgi = self.app.wsgi()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2023-12-11 13:13:31     self.callable = self.load()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2023-12-11 13:13:31     return self.load_wsgiapp()
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2023-12-11 13:13:31     return util.import_app(self.app_uri)
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
2023-12-11 13:13:31     mod = importlib.import_module(module)
2023-12-11 13:13:31   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-12-11 13:13:31     return _bootstrap._gcd_import(name[level:], package, level)
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-12-11 13:13:31   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-12-11 13:13:31   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-12-11 13:13:31   File "/app/main.py", line 12, in <module>
2023-12-11 13:13:31     from config import CONFIG,logger,MANAGER_ID
2023-12-11 13:13:31   File "/app/config.py", line 65, in <module>
2023-12-11 13:13:31     CONFIG = ManagerConfig()
2023-12-11 13:13:31   File "/app/config.py", line 27, in __init__
2023-12-11 13:13:31     self.cfg:Dict = yaml.load(open(config_file_path,"r",encoding="utf-8").read(), Loader=yaml.FullLoader)
2023-12-11 13:13:31 FileNotFoundError: [Errno 2] No such file or directory: 'E:\\manager.yml'
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [8] [INFO] Worker exiting (pid: 8)
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [7] [INFO] Worker exiting (pid: 7)
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [1] [ERROR] Shutting down: Master
2023-12-11 13:13:31 [2023-12-11 05:13:31 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by dlmty** [comment]
我也遇到同样的bug。

**Comment by Umpire2018** [comment]
1. 请在根目录下运行 `docker-compose up` 。
2. 请不要直接修改源代码，除非您确信能解决问题。

**Comment by jfo888** [comment]
我在e:\rengongzhineng\XAgent-main下运行docker-compose build和docker-compose up不会出现No such file or directory报错了，但是又出现了dependency failed to start: container xagent-main-xagent-mysql-1 is unhealthy的报错，然后在e:\rengongzhineng\XAgent-main运行docker exec XAgent-Server systemctl start nginx，出现Error response from daemon: Container db34c43d67800b1790bcd85293818f501eba6d5fe823671b6ec57c0e5f28abbd is not running的报错，这又是怎么回事呢

**Comment by Umpire2018** [comment]
我们最近推送了针对此问题的更新，请重新拉取代码后进行使用。
