### ISSUE TITLE
运行卡死并且报错

### ISSUE THREAD

**Issue by leap233** [OpenBMB/XAgent#382]
## Issue Description / 问题描述
网页和命令行运行时卡死,并且报错

## Steps to Reproduce / 复现步骤
这是我的config.yml,除此之外我没有做任何修改
``` 
api_keys:
  gpt-3.5-turbo-16k:
      # you can use any kwargs supported by openai.ChatCompletion here
    - api_key: sk-xxxxxxx(我已经填写了有效的key)
      model: gpt-3.5-turbo-16k
      organization: xxxxxx
    - api_key: sk-xxxxxxx(我已经填写了有效的key)
      api_base: https://example.com
      api_type: azure
      api_version: 2023-07-01-preview
      engine: GPT-35-Turbo-16k

  gpt-4:    
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4
  gpt-4-32k:
    - api_key: sk-xxxxx
      organization: org-xxxxx
      model: gpt-4-32k
    - api_key: sk-xxxxx
      organization: org-xxxxxx
      model: gpt-4-32k

default_request_type: openai # or xagent

default_completion_kwargs:
  model: gpt-3.5-turbo-16k
  temperature: 0.2
  request_timeout: 60

enable_summary: true
summary:
  single_action_max_length: 2048
  max_return_length: 12384

use_selfhost_toolserver: true
selfhost_toolserver_url: http://localhost:8080

max_retry_times: 5
max_subtask_chain_length: 15
max_plan_refine_chain_length: 3
max_plan_tree_depth: 3
max_plan_tree_width: 5
max_plan_length: 8192

rapidapi_retrieve_tool_count: 0

enable_ask_human_for_help: False

tool_blacklist:
  - FileSystemEnv_print_filesys_struture

record_dir:

experiment:
  redo_action: false
```

在我通过5173端口的网页端进行对话时,后台显示卡在了第一步。
(网页选项: Agent=XAgent , Mode=Auto,问题:告诉我中国的首都是哪里)
```
XAgent-Server        | -=-=-=-=-=-=-= BEGIN QUERY SOVLING -=-=-=-=-=-=-=  
XAgent-Server        | Role  Assistant
XAgent-Server        | Task  Tell me the capital of China
XAgent-Server        | Plan 
XAgent-Server        |  1.Pay attention to the language in inital goal, alway answer with the same language of the inital goal given. 
XAgent-Server        | -=-=-=-=-=-=-= GENERATE INITIAL_PLAN -=-=-=-=-=-=-= 
```
接着几十分钟后,会出现错误:
```
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgentServer/server.py", line 99, in interact
XAgent-Server        |     task_handler.outer_loop()
XAgent-Server        |   File "/app/XAgent/workflow/task_handler.py", line 82, in outer_loop
XAgent-Server        |     self.plan_agent.initial_plan_generation(
XAgent-Server        |   File "/app/XAgent/workflow/plan_exec.py", line 164, in initial_plan_generation
XAgent-Server        |     new_message , _ = agent.parse(
XAgent-Server        |   File "/app/XAgent/agent/plan_generate_agent/agent.py", line 49, in parse
XAgent-Server        |     return self.generate(
XAgent-Server        |   File "/app/XAgent/agent/base_agent.py", line 121, in generate
XAgent-Server        |     response = objgenerator.chatcompletion(
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server        |     return self(f, *args, **kw)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server        |     do = self.iter(retry_state=retry_state)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
XAgent-Server        |     return fut.result()
XAgent-Server        |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server        |     return self.__get_result()
XAgent-Server        |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server        |     raise self._exception
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server        |     result = fn(*args, **kwargs)
XAgent-Server        |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 66, in chatcompletion
XAgent-Server        |     raise e
XAgent-Server        |   File "/app/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
XAgent-Server        |     response = self._get_chatcompletion_request_func(request_type)(**kwargs)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
XAgent-Server        |     return self(f, *args, **kw)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
XAgent-Server        |     do = self.iter(retry_state=retry_state)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
XAgent-Server        |     raise retry_exc.reraise()
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
XAgent-Server        |     raise self.last_attempt.result()
XAgent-Server        |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
XAgent-Server        |     return self.__get_result()
XAgent-Server        |   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
XAgent-Server        |     raise self._exception
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
XAgent-Server        |     result = fn(*args, **kwargs)
XAgent-Server        |   File "/app/XAgent/ai_functions/request/openai.py", line 161, in chatcompletion_request
XAgent-Server        |     completions = client.chat.completions.create(**chatcompletion_kwargs)
XAgent-Server        |   File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 300, in wrapper
XAgent-Server        |     raise TypeError(msg)
XAgent-Server        | TypeError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given
XAgent-Server        | 
XAgent-Server        | The above exception was the direct cause of the following exception:
XAgent-Server        | 
XAgent-Server        | Traceback (most recent call last):
XAgent-Server        |   File "/app/XAgentServer/application/websockets/base.py", line 324, in task_handler
XAgent-Server        |     server.interact(interaction=interaction)
XAgent-Server        |   File "/app/XAgentServer/server.py", line 101, in interact
XAgent-Server        |     raise XAgentRunningError(str(e)) from e
XAgent-Server        | XAgentServer.exts.exception_ext.XAgentRunningError: Missing required arguments; Expected either ('messages' and 'model') or ('messages', 'model' and 'stream') arguments to be given
```

在我通过命令行
```
python run.py --task "告诉我中国的首都" --config-file "assets/config.yml"
```
执行时,发生以下错误
(我的openai版本是 1.9.0 ,会和openai的版本问题有关吗?)
```
  chatcompletion: using gpt-3.5-turbo-16k

  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
  chatcompletion: using gpt-3.5-turbo-16k
Traceback (most recent call last):
  File "/data/wd/开源项目测试/XAgent-main/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
    response = self._get_chatcompletion_request_func(request_type)(**kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/data/wd/开源项目测试/XAgent-main/XAgent/ai_functions/request/openai.py", line 191, in chatcompletion_request
    completions = client.chat.completions.create(**chatcompletion_kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 648, in create
    return self._post(
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 1179, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 868, in request
    return self._request(
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 959, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Not Found</title>
        </head>
        <body>
                <h1>404 - Not Found</h1>
                <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script>
        </body>
</html>
chatcompletion error: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <title>404 - Not Found</title> </head> <body> <h1>404 - Not Found</h1> <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script> </body> </html> 
Traceback (most recent call last):
  File "/data/wd/开源项目测试/XAgent-main/XAgentServer/server.py", line 104, in interact
    task_handler.outer_loop()
  File "/data/wd/开源项目测试/XAgent-main/XAgent/workflow/task_handler.py", line 82, in outer_loop
    self.plan_agent.initial_plan_generation(
  File "/data/wd/开源项目测试/XAgent-main/XAgent/workflow/plan_exec.py", line 164, in initial_plan_generation
    new_message , _ = agent.parse(
  File "/data/wd/开源项目测试/XAgent-main/XAgent/agent/plan_generate_agent/agent.py", line 49, in parse
    return self.generate(
  File "/data/wd/开源项目测试/XAgent-main/XAgent/agent/base_agent.py", line 121, in generate
    response = objgenerator.chatcompletion(
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/data/wd/开源项目测试/XAgent-main/XAgent/ai_functions/request/obj_generator.py", line 66, in chatcompletion
    raise e
  File "/data/wd/开源项目测试/XAgent-main/XAgent/ai_functions/request/obj_generator.py", line 60, in chatcompletion
    response = self._get_chatcompletion_request_func(request_type)(**kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/data/wd/开源项目测试/XAgent-main/XAgent/ai_functions/request/openai.py", line 191, in chatcompletion_request
    completions = client.chat.completions.create(**chatcompletion_kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 648, in create
    return self._post(
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 1179, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 868, in request
    return self._request(
  File "/data/wd/miniconda3/envs/Xagent/lib/python3.10/site-packages/openai/_base_client.py", line 959, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Not Found</title>
        </head>
        <body>
                <h1>404 - Not Found</h1>
                <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script>
        </body>
</html>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/wd/开源项目测试/XAgent-main/command.py", line 273, in task_handler
    server.interact(interaction=interaction)
  File "/data/wd/开源项目测试/XAgent-main/XAgentServer/server.py", line 106, in interact
    raise XAgentRunningError(str(e)) from e
XAgentServer.exts.exception_ext.XAgentRunningError: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Not Found</title>
        </head>
        <body>
                <h1>404 - Not Found</h1>
                <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script>
        </body>
</html>
Error in task_handler of 6e1bb2e0e017441aab52192cfa354b86: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>404 - Not Found</title>
        </head>
        <body>
                <h1>404 - Not Found</h1>
                <script type="text/javascript" src="//obj.ac.bcon.ecdns.net/ec_tpm_bcon.js"></script>
        </body>
</html> 
```

## Expected Behavior / 预期行为
网页端流程正常,呈现官网示例的效果
命令行流程正常

## Environment / 环境信息
- Operating System / 操作系统：ubuntu="18.04.6 LTS (Bionic Beaver)"
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：Docker version 24.0.2, build cb74dfc

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。

## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by xxx1099836595** [comment]
这个问题怎么解决的呢，我也遇到了类似的问题
``
