### ISSUE TITLE
源码构建docker compose build时候[ 2/41] Cythonizing spacy/kb.pyx错误

### ISSUE THREAD

**Issue by zhangcheng0111** [OpenBMB/XAgent#403]
## Issue Description / 问题描述
Please provide a detailed description of the error or issue you encountered. / 请详细描述您遇到的错误或问题。
在使用源码构建docker compose build时候报错，报错见错误日志与截图

## Steps to Reproduce / 复现步骤
Please provide the specific steps to reproduce the error. / 请提供复现错误的具体步骤。
直接使用docker compose up --bulid
## Expected Behavior / 预期行为
Describe the behavior you expected to see. / 请描述您期望的正确行为。
能够正确安装
## Environment / 环境信息
- Operating System / 操作系统：windows 11 WSL 2
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：

## Error Screenshots or Logs / 错误截图或日志
If possible, please provide relevant screenshots or logs of the error. / 如果可能，请提供相关的错误截图或日志文件。
208.1       [ 1/41] Cythonizing spacy/attrs.pyx
208.1       [ 2/41] Cythonizing spacy/kb.pyx
208.1       Traceback (most recent call last):
208.1         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
208.1           main()
208.1         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
208.1           json_out['return_val'] = hook(**hook_input['kwargs'])
208.1         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
208.1           return hook(config_settings)
208.1         File "/tmp/pip-build-env-2x37m6bt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
208.1           return self._get_build_requires(config_settings, requirements=['wheel'])    
208.1         File "/tmp/pip-build-env-2x37m6bt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
208.1           self.run_setup()
208.1         File "/tmp/pip-build-env-2x37m6bt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
208.1           exec(code, locals())
208.1         File "<string>", line 224, in <module>
208.1         File "<string>", line 211, in setup_package
208.1         File "/tmp/pip-build-env-2x37m6bt/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
208.1           cythonize_one(*args)
208.1         File "/tmp/pip-build-env-2x37m6bt/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
208.1           raise CompileError(None, pyx_file)
208.1       Cython.Compiler.Errors.CompileError: spacy/kb.pyx
208.1       [end of output]
208.1
208.1   note: This error originates from a subprocess, and is likely not a problem with pip.
208.1 error: subprocess-exited-with-error
208.1
208.1 × Getting requirements to build wheel did not run successfully.
208.1 │ exit code: 1
208.1 ╰─> See above for output.
208.1
208.1 note: This error originates from a subprocess, and is likely not a problem with pip.  
208.2
208.2 [notice] A new release of pip is available: 23.0.1 -> 24.0
208.2 [notice] To update, run: pip install --upgrade pip
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
## Additional Notes / 其他备注
If you have any additional information or notes, please add them here. / 如果有其他补充信息，请在此处添加。

**Comment by zhangcheng0111** [comment]
还有一个现象是在构建时候，会从spacy的3.3.2一直向下换版本，换到3.0.6时候进行报错

**Comment by zhangcheng0111** [comment]
放弃源码编译后，改用拉去docker镜像的方式，报错以下内容
dependency failed to start: container xagentproject-xagent-mysql-1 exited (1)

**Comment by SOMMTA** [comment]
@zhangcheng0111  在requirement.txt文件中加入Cython，安装并更新这个库以后，解决了scapy的兼容性问题，docker compose build成功，但是docker compose up 仍出现mysql错误信息，我打算单独构建这个镜像
