### ISSUE TITLE
Maximum Context Lenght Problem

### ISSUE THREAD

**Issue by pedrocacintra** [OpenBMB/XAgent#43]
After I spent a prolong time in auto reflection and burneda lot of tokens, it reached max context lenght, then tried to acess gpt-4-32k and couldnt, then it just broke.

max context length reached, retrying with gpt-4-32k
  Traceback (most recent call last):
  File "D:\AI\XAgent\XAgent\ai_functions\request\openai.py", line 86, in openai_chatcompletion_request
    raise InvalidRequestError('maximum context length exceeded',None)
openai.error.InvalidRequestError: maximum context length exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\XAgent\XAgentServer\server.py", line 104, in interact
    await task_handler.outer_loop_async()
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 146, in outer_loop_async
    search_method = await self.inner_loop_async(self.now_dealing_task)
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 292, in inner_loop_async
    await search_method.run_async(config=self.config,
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 64, in run_async
    await self.generate_chain_async(config, agent, task_handler, function_list, tool_functions_description_list, task_id)
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 290, in generate_chain_async
    LLM_code, new_message, tokens = agent.parse(
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\agent\tool_agent\agent.py", line 38, in parse
    response = _chat_completion_request(
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\agent\utils.py", line 48, in _chat_completion_request
    response = openai_chatcompletion_request(**json_data)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\ai_functions\request\openai.py", line 103, in openai_chatcompletion_request
    response = openai.ChatCompletion.create(**chatcompletion_kwargs)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4-32k` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

Traceback (most recent call last):
  File "D:\AI\XAgent\XAgent\ai_functions\request\openai.py", line 86, in openai_chatcompletion_request
    raise InvalidRequestError('maximum context length exceeded',None)
openai.error.InvalidRequestError: maximum context length exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\XAgent\run.py", line 48, in <module>
    cmd.start(
  File "D:\AI\XAgent\command.py", line 163, in start
    self.run({
  File "D:\AI\XAgent\command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\AI\XAgent\XAgentServer\server.py", line 107, in interact
    raise e
  File "D:\AI\XAgent\XAgentServer\server.py", line 104, in interact
    await task_handler.outer_loop_async()
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 146, in outer_loop_async
    search_method = await self.inner_loop_async(self.now_dealing_task)
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 292, in inner_loop_async
    await search_method.run_async(config=self.config,
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 64, in run_async
    await self.generate_chain_async(config, agent, task_handler, function_list, tool_functions_description_list, task_id)
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 290, in generate_chain_async
    LLM_code, new_message, tokens = agent.parse(
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\agent\tool_agent\agent.py", line 38, in parse
    response = _chat_completion_request(
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\agent\utils.py", line 48, in _chat_completion_request
    response = openai_chatcompletion_request(**json_data)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "D:\AI\XAgent\myenv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "D:\AI\XAgent\XAgent\ai_functions\request\openai.py", line 103, in openai_chatcompletion_request
    response = openai.ChatCompletion.create(**chatcompletion_kwargs)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "D:\AI\XAgent\myenv\lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4-32k` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
(myenv) PS D:\AI\XAgent>

**Comment by luyaxi** [comment]
Please make sure the gpt-4-32k token is valid in `config.yml` or delete the entire gpt-4-32k entry, in which case the will try gpt-3.5-turbo-16k as a back plan. You can also try to low down `summary.max_return_length` or `max_plan_length` to fixs the problem
