### ISSUE TITLE
charmap codec cant encode some characters?

### ISSUE THREAD

**Issue by MrXandbadas** [OpenBMB/XAgent#50]
Hello, after installing and trying to run the Agent i receive an error!

```
   json.dump(tool_record, writer, indent=2, ensure_ascii=False)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode     
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 80-81: character maps to <undefined>
```

**Comment by pedrocacintra** [comment]
Experienced similar issue today:
  Traceback (most recent call last):
  File "D:\AI\XAgent\XAgentServer\server.py", line 104, in interact
    await task_handler.outer_loop_async()
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 146, in outer_loop_async
    search_method = await self.inner_loop_async(self.now_dealing_task)
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 292, in inner_loop_async
    await search_method.run_async(config=self.config,
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 64, in run_async
    await self.generate_chain_async(config, agent, task_handler, function_list, tool_functions_description_list, task_id)
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 328, in generate_chain_async
    tool_output, tool_output_status_code, need_for_plan_refine, using_tools = function_handler.handle_tool_call(
  File "D:\AI\XAgent\XAgent\tool_call_handle.py", line 360, in handle_tool_call
    command_result, tool_output_status_code, = toolserver_interface.execute_command_client(
  File "D:\AI\XAgent\XAgent\tool_call_handle.py", line 240, in execute_command_client
    recorder.regist_tool_server(url=url,
  File "D:\AI\XAgent\XAgent\running_recorder.py", line 135, in regist_tool_server
    json.dump(tool_record, writer, indent=2, ensure_ascii=False)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u200a' in position 12024: character maps to <undefined>

Traceback (most recent call last):
  File "D:\AI\XAgent\run.py", line 48, in <module>
    cmd.start(
  File "D:\AI\XAgent\command.py", line 163, in start
    self.run({
  File "D:\AI\XAgent\command.py", line 137, in run
    asyncio.run(server.interact(interaction=interaction))
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\AI\XAgent\XAgentServer\server.py", line 107, in interact
    raise e
  File "D:\AI\XAgent\XAgentServer\server.py", line 104, in interact
    await task_handler.outer_loop_async()
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 146, in outer_loop_async
    search_method = await self.inner_loop_async(self.now_dealing_task)
  File "D:\AI\XAgent\XAgent\workflow\task_handler.py", line 292, in inner_loop_async
    await search_method.run_async(config=self.config,
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 64, in run_async
    await self.generate_chain_async(config, agent, task_handler, function_list, tool_functions_description_list, task_id)
  File "D:\AI\XAgent\XAgent\inner_loop_search_algorithms\ReACT.py", line 328, in generate_chain_async
    tool_output, tool_output_status_code, need_for_plan_refine, using_tools = function_handler.handle_tool_call(
  File "D:\AI\XAgent\XAgent\tool_call_handle.py", line 360, in handle_tool_call
    command_result, tool_output_status_code, = toolserver_interface.execute_command_client(
  File "D:\AI\XAgent\XAgent\tool_call_handle.py", line 240, in execute_command_client
    recorder.regist_tool_server(url=url,
  File "D:\AI\XAgent\XAgent\running_recorder.py", line 135, in regist_tool_server
    json.dump(tool_record, writer, indent=2, ensure_ascii=False)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Users\pedro\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u200a' in position 12024: character maps to <undefined>
(myenv) PS D:\AI\XAgent> b

**Comment by luyaxi** [comment]
We've upload a hotfix for this, could you provide your running case to help us verify the problem?

**Comment by MrXandbadas** [comment]
Running querys that will generate web searches. Searching for information about github projects. (autogen/memgpt) the big few at the moment xD
I havnt had a problem since pulling to the latest so i'll go ahead and close this as this bug seeminly has been squashed
