### ISSUE TITLE
前端页面发送消息失败，但是在命令行是可以访问8080端口和openai。

### ISSUE THREAD

**Issue by shalimujiang** [OpenBMB/XAgent#95]
## Issue Description / 问题描述
我在WSL2-Ubuntu20.04系统上git clone项目代码：
1，之前在命令行运行代码 `python run.py --task "put your task here" --model "gpt-4" --config_file "assets/config.yml"`会出现两种情况

- 第一，能访问Localhost:8080，但不能请求OpenAI，会在命令行输出结果上呆很久，一直不输出：
```
-=-=-=-=-=-=-= GENERATE INITIAL_PLAN -=-=-=-=-=-=-= 
Constructing an Agent:  PlanGenerateAgent
  chatcompletion: using gpt-3.5-turbo-16k
```

- 第二，我修改了WSL2中./bashrc加上代理和本地访问跳过，就可以输入上面的命令就可以访问localhost:8080和openai了：
```
vim ~/.bashrc
# 为了访问OpenAI的请求设置clash代理
export http_proxy=http://proxy_server:proxy_port
export https_proxy=http://proxy_server:proxy_port
# 为了访问本地localhost:8080
export no_proxy=localhost,127.0.0.1,::1
source ~/.bashrc
```

以上都是在**命令行**的复现结果，现在我想启动**Web UI**来看看并在另一个命令行输入了`docker exec XAgent-Server systemctl start nginx`，打开localhost:5173网页发现输入完点击发送，页面就会停在某一页面没有相应。我想是不是因为我的**WSL2系统**的原因，导致了Web UI不能正常运行。**我应该怎么设置我的配置文件**

## Steps to Reproduce / 复现步骤
**这是命令行输出的正常结果：**
![image](https://github.com/OpenBMB/XAgent/assets/75249643/d2bf5716-2034-4e1c-b453-069adbd8abc7)

**这是在网页端的错误结果：**
![image](https://github.com/OpenBMB/XAgent/assets/75249643/2faa4290-fd72-4e2d-a32e-6189f0392fc2)

## Expected Behavior / 预期行为
能正常访问Web UI

## Environment / 环境信息
- Operating System / 操作系统：windows10->**WSL2**->Ubuntu20.04
- Python Version / Python 版本：3.10
- Other Relevant Information / 其他相关信息：
windows - Docker：
Docker version 24.0.6, build ed223bc
Docker Compose version v2.22.0-desktop.2

## Error Screenshots or Logs / 错误截图或日志
**XAgent-Server.log:**
2023-10-23 19:06:05 INFO:     Will watch for changes in these directories: ['/app']
2023-10-23 19:06:05 INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
2023-10-23 19:06:05 INFO:     Started reloader process [1] using StatReload
2023-10-23 19:06:06 INFO:     Started server process [9]
2023-10-23 19:06:06 INFO:     Waiting for application startup.
2023-10-23 19:06:06 INFO:     Application startup complete.
2023-10-23 19:08:39 INFO:     ('172.26.0.1', 43476) - "WebSocket /ws/03d017c0-7090-4f48-827f-87fddd486e35?user_id=admin&token=xagent-admin&description=%E5%B8%AE%E6%88%91%E5%86%99%E4%B8%80%E7%AF%87%E4%BD%9C%E6%96%87%EF%BC%9A%E6%88%91%E7%9A%84%E4%B8%80%E6%97%A5" [accepted]
2023-10-23 19:08:39 INFO:     connection open
2023-10-23 19:08:42   XAgent Service Startup Param:
2023-10-23 19:08:42             app: app:app
2023-10-23 19:08:42             prod: False
2023-10-23 19:08:42             base_dir: XAgentServer
2023-10-23 19:08:42             use_redis: False
2023-10-23 19:08:42             recorder_root_dir: running_records
2023-10-23 19:08:42             default_login: True
2023-10-23 19:08:42             check_running: False
2023-10-23 19:08:42             host: 0.0.0.0
2023-10-23 19:08:42             port: 8090
2023-10-23 19:08:42             debug: True
2023-10-23 19:08:42             reload: True
2023-10-23 19:08:42             workers: 1
2023-10-23 19:08:42             DB: <class 'XAgentServer.envs.XAgentServerEnv.DB'>
2023-10-23 19:08:42             Redis: <class 'XAgentServer.envs.XAgentServerEnv.Redis'>
2023-10-23 19:08:42             Email: <class 'XAgentServer.envs.XAgentServerEnv.Email'>
2023-10-23 19:08:42             Upload: <class 'XAgentServer.envs.XAgentServerEnv.Upload'>
2023-10-23 19:08:42   init websocket_queue
2023-10-23 19:08:42 XAgentServer is running on 0.0.0.0:8090  
2023-10-23 19:08:42 Default user: admin, token: xagent-admin, you can use it to login  
2023-10-23 19:08:42   Create task for pong broadcast
2023-10-23 19:08:42 init a websocket manager  
2023-10-23 19:08:42 init a thread pool executor, max_workers: 1  
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   init localstorage connection: users.json
2023-10-23 19:08:42   init localstorage connection: interaction.json
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42   pong broadcast for active connections: 0
2023-10-23 19:08:42 Receive connection from 03d017c0-7090-4f48-827f-87fddd486e35:   user_id: admin, token: xagent-admin, description: 帮我写一篇作文：我的一日
2023-10-23 19:08:42   websocket 03d017c0-7090-4f48-827f-87fddd486e35 connected
2023-10-23 19:08:42 Receive data from 03d017c0-7090-4f48-827f-87fddd486e35:   {"type":"data","args":{"goal":"帮我写一篇作文：我的一日"},"agent":"agent","mode":"auto","file_list":[]}
2023-10-23 19:08:42   Register parameter: {'interaction_id': '03d017c0-7090-4f48-827f-87fddd486e35', 'parameter_id': '90ea91687192440e806bdc0e6de503cf', 'args': {'goal': '帮我写一篇作文：我的一日'}} into interaction of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42   init interaction: 03d017c0-7090-4f48-827f-87fddd486e35
2023-10-23 19:08:42   Register logger into interaction of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42   Register io into interaction of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42   Register db into interaction of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42   Register logger into XAgentServer of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42   Start a new thread to run interaction of 03d017c0-7090-4f48-827f-87fddd486e35, done!
2023-10-23 19:08:42 Constructing an AgentDispatcher:  XAgentDispatcher
2023-10-23 19:08:42 ---config file---
2023-10-23 19:08:42 assets/config.yml
2023-10-23 19:08:42 ---args---
2023-10-23 19:08:42 {}
2023-10-23 19:08:42   server is running, the start query is 帮我写一篇作文：我的一日
2023-10-23 19:08:42   {
2023-10-23 19:08:42   "api_keys": {
2023-10-23 19:08:42     "gpt-3.5-turbo-16k": [
2023-10-23 19:08:42       {
2023-10-23 19:08:42         "api_key": "sk-******",
2023-10-23 19:08:42         "organization": "org-****",
2023-10-23 19:08:42         "model": "gpt-3.5-turbo-16k"
2023-10-23 19:08:42       },
2023-10-23 19:08:42       {
2023-10-23 19:08:42         "api_key": "sk-**********",
2023-10-23 19:08:42         "organization": "org-******",
2023-10-23 19:08:42         "model": "gpt-3.5-turbo-16k"
2023-10-23 19:08:42       }
2023-10-23 19:08:42     ]
2023-10-23 19:08:42   },
2023-10-23 19:08:42   "default_request_type": "openai",
2023-10-23 19:08:42   "default_completion_kwargs": {
2023-10-23 19:08:42     "model": "gpt-3.5-turbo-16k",
2023-10-23 19:08:42     "temperature": 0.2,
2023-10-23 19:08:42     "request_timeout": 60
2023-10-23 19:08:42   },
2023-10-23 19:08:42   "enable_summary": true,
2023-10-23 19:08:42   "summary": {
2023-10-23 19:08:42     "single_action_max_length": 4096,
2023-10-23 19:08:42     "max_return_length": 8192
2023-10-23 19:08:42   },
2023-10-23 19:08:42   "use_selfhost_toolserver": true,
2023-10-23 19:08:42   "selfhost_toolserver_url": "http://localhost:8080",
2023-10-23 19:08:42   "max_retry_times": 3,
2023-10-23 19:08:42   "max_subtask_chain_length": 15,
2023-10-23 19:08:42   "max_plan_refine_chain_length": 3,
2023-10-23 19:08:42   "max_plan_tree_depth": 3,
2023-10-23 19:08:42   "max_plan_tree_width": 5,
2023-10-23 19:08:42   "max_plan_length": 4096,
2023-10-23 19:08:42   "rapidapi_retrieve_tool_count": 0,
2023-10-23 19:08:42   "enable_ask_human_for_help": false,
2023-10-23 19:08:42   "tool_blacklist": [
2023-10-23 19:08:42     "FileSystemEnv_print_filesys_struture"
2023-10-23 19:08:42   ],
2023-10-23 19:08:42   "record_dir": null
2023-10-23 19:08:42 }
2023-10-23 19:08:42 Human-In-The-Loop  False
2023-10-23 19:08:43 ERROR:    Exception in ASGI application
2023-10-23 19:08:43 Traceback (most recent call last):
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
2023-10-23 19:08:43     sock = connection.create_connection(
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
2023-10-23 19:08:43     raise err
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
2023-10-23 19:08:43     sock.connect(sa)
2023-10-23 19:08:43 ConnectionRefusedError: [Errno 111] Connection refused
2023-10-23 19:08:43 
2023-10-23 19:08:43 The above exception was the direct cause of the following exception:
2023-10-23 19:08:43 
2023-10-23 19:08:43 Traceback (most recent call last):
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
2023-10-23 19:08:43     response = self._make_request(
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
2023-10-23 19:08:43     conn.request(
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
2023-10-23 19:08:43     self.endheaders()
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
2023-10-23 19:08:43     self._send_output(message_body, encode_chunked=encode_chunked)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
2023-10-23 19:08:43     self.send(msg)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/http/client.py", line 976, in send
2023-10-23 19:08:43     self.connect()
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
2023-10-23 19:08:43     self.sock = self._new_conn()
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
2023-10-23 19:08:43     raise NewConnectionError(
2023-10-23 19:08:43 urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f646693ad70>: Failed to establish a new connection: [Errno 111] Connection refused
2023-10-23 19:08:43 
2023-10-23 19:08:43 The above exception was the direct cause of the following exception:
2023-10-23 19:08:43 
2023-10-23 19:08:43 Traceback (most recent call last):
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2023-10-23 19:08:43     resp = conn.urlopen(
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
2023-10-23 19:08:43     retries = retries.increment(
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
2023-10-23 19:08:43     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2023-10-23 19:08:43 urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f646693ad70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-10-23 19:08:43 
2023-10-23 19:08:43 During handling of the above exception, another exception occurred:
2023-10-23 19:08:43 
2023-10-23 19:08:43 Traceback (most recent call last):
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
2023-10-23 19:08:43     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-10-23 19:08:43     return await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
2023-10-23 19:08:43     await super().__call__(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-10-23 19:08:43     await self.middleware_stack(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
2023-10-23 19:08:43     await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
2023-10-23 19:08:43     await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 26, in __call__
2023-10-23 19:08:43     await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-10-23 19:08:43     raise exc
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-10-23 19:08:43     await self.app(scope, receive, sender)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-10-23 19:08:43     raise e
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-10-23 19:08:43     await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-10-23 19:08:43     await route.handle(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
2023-10-23 19:08:43     await self.app(scope, receive, send)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 88, in dispatch
2023-10-23 19:08:43     raise exc
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/starlette/endpoints.py", line 80, in dispatch
2023-10-23 19:08:43     await self.on_receive(websocket, data)
2023-10-23 19:08:43   File "/app/app.py", line 628, in on_receive
2023-10-23 19:08:43     await asyncio.create_task(self.do_running_long_task(parameter))
2023-10-23 19:08:43   File "/app/app.py", line 688, in do_running_long_task
2023-10-23 19:08:43     await task
2023-10-23 19:08:43   File "/app/XAgentServer/server.py", line 64, in interact
2023-10-23 19:08:43     toolserver_interface.lazy_init(config=config)
2023-10-23 19:08:43   File "/app/XAgent/tool_call_handle.py", line 63, in lazy_init
2023-10-23 19:08:43     response = requests.post(f'{self.url}/get_cookie',)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
2023-10-23 19:08:43     return request("post", url, data=data, json=json, **kwargs)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
2023-10-23 19:08:43     return session.request(method=method, url=url, **kwargs)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2023-10-23 19:08:43     resp = self.send(prep, **send_kwargs)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2023-10-23 19:08:43     r = adapter.send(request, **kwargs)
2023-10-23 19:08:43   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
2023-10-23 19:08:43     raise ConnectionError(e, request=request)
2023-10-23 19:08:43 requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /get_cookie (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f646693ad70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-10-23 19:08:43 INFO:     connection closed

**xagent.log:**
2023-10-23 19:10:51 XAgent-Server               | ToolServer connected in  http://localhost:8080
2023-10-23 19:10:51 XAgent-Server               | Disconnect with client 03d017c0-7090-4f48-827f-87fddd486e35:   
2023-10-23 19:10:51 XAgent-Server               |   websocket 03d017c0-7090-4f48-827f-87fddd486e35 remove from active connections
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:10:51 XAgent-Server               | INFO:     172.26.0.1:40844 - "GET / HTTP/1.1" 404 Not Found
2023-10-23 19:11:09 XAgent-Server               | INFO:     ('172.26.0.1', 38850) - "WebSocket /ws/5e902cbf-5fb0-4f9e-83bd-28f8567cace2?user_id=admin&token=xagent-admin&description=%E5%B8%AE%E6%88%91%E5%86%99%E4%B8%80%E7%AF%87%E4%BD%9C%E6%96%87%EF%BC%9A%E6%88%91%E7%9A%84%E4%B8%80%E6%97%A5" [accepted]
2023-10-23 19:11:09 XAgent-Server               | INFO:     connection open
2023-10-23 19:11:09 XAgent-Server               |   pong broadcast for active connections: 0
2023-10-23 19:11:09 XAgent-Server               | Receive connection from 5e902cbf-5fb0-4f9e-83bd-28f8567cace2:   user_id: admin, token: xagent-admin, description: 帮我写一篇作文：我的一日
2023-10-23 19:11:09 XAgent-Server               |   websocket 5e902cbf-5fb0-4f9e-83bd-28f8567cace2 connected
2023-10-23 19:11:09 XAgent-Server               | Receive data from 5e902cbf-5fb0-4f9e-83bd-28f8567cace2:   {"type":"data","args":{"goal":"帮我写一篇作文：我的一日"},"agent":"agent","mode":"auto","file_list":[]}
2023-10-23 19:11:09 XAgent-Server               |   Register parameter: {'interaction_id': '5e902cbf-5fb0-4f9e-83bd-28f8567cace2', 'parameter_id': '750b24af5bdb44718440fcda25c5d0a6', 'args': {'goal': '帮我写一篇作文：我的一日'}} into interaction of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!
2023-10-23 19:11:09 XAgent-Server               |   init interaction: 5e902cbf-5fb0-4f9e-83bd-28f8567cace2
2023-10-23 19:11:09 XAgent-Server               |   Register logger into interaction of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!
2023-10-23 19:11:09 XAgent-Server               |   Register io into interaction of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!
2023-10-23 19:11:09 XAgent-Server               |   Register db into interaction of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!
2023-10-23 19:11:09 XAgent-Server               |   Register logger into XAgentServer of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!
2023-10-23 19:11:09 XAgent-Server               |   Start a new thread to run interaction of 5e902cbf-5fb0-4f9e-83bd-28f8567cace2, done!

如果需要我还可以提供其他log文件的内容

## Additional Notes / 其他备注
**1，命令行可以访问后端内容，但是网页端不行。
2，命令行可以访问的原因是WSL2的代理配置文件修改过，但是网页端的还没有，对网页端的哪个部分要修改并不太清楚**

**Comment by luyaxi** [comment]
你需要同时forward 8090端口来使用网页

**Comment by shalimujiang** [comment]
> 你需要同时forward 8090端口来使用网页

你好，我不太清楚你这个同时forward 8090是什么意思，麻烦你指一下我应该修改哪一个配置文件的内容？万分感谢

**Comment by luyaxi** [comment]
如果你在使用vscode，可以尝试通过在端口选项卡中添加转发端口实现

**Comment by shalimujiang** [comment]
> 你需要同时forward 8090端口来使用网页

这样吗？但是还是不行
![image](https://github.com/OpenBMB/XAgent/assets/75249643/915d4a32-1eb0-4971-8125-f7229757f879)

**Comment by luyaxi** [comment]
请使用最新的代码，并确保docker-compose.yml中`TOOLSERVER_URL=http://ToolServerManager:8080`，确保XAgentServer与ToolServer都在`tool-server-network`网络下

**Comment by shalimujiang** [comment]
> 请使用最新的代码，并确保docker-compose.yml中`TOOLSERVER_URL=http://ToolServerManager:8080`，确保XAgentServer与ToolServer都在`tool-server-network`网络下

可以了

**Comment by shalimujiang** [comment]
> 请使用最新的代码，并确保docker-compose.yml中`TOOLSERVER_URL=http://ToolServerManager:8080`，确保XAgentServer与ToolServer都在`tool-server-network`网络下

万分感谢
